### ISSUE TITLE
msvcp120.dll   missing  under Windows 8.1  (.zip and .exe version)  fix inside

### ISSUE THREAD

**Issue by ghost** [todbot/blink1#122]
Hello @todbot   ,    when you try to run the new version, it happens.a missing dll error .

I have this installed:  (many games need them) 
- Microsoft Visual C++ 2010 Redistributable Package (x86)  
- Microsoft Visual C++ 2010 Redistributable Package (x64) 
## FIX ) The missing DLL is from: 
- Microsoft Visual C++ Redistributable Packages for Visual Studio 2013
  http://www.microsoft.com/en-gb/download/details.aspx?id=40784
## You can also see a list of dll from here:

http://msdn.microsoft.com/en-us/library/8kche8ah.aspx

Thanks for the patterns,  Im doing a few more  (Lava, rain,  storm...... )  I will send it soon!

**Comment by arushkandra** [comment]
Thank You So Muchhh
